services:
  cassandra_dc1_rack1:
    container_name: dc1_rack1
    hostname: node1
    image: cassandra:4.0.4
    environment:
      CASSANDRA_CLUSTER_NAME: StudentsCluster
      CASSANDRA_DC: dc1
      CASSANDRA_RACK: rack1
      CASSANDRA_NUM_TOKENS: 32
      CASSANDRA_SEEDS: 10.0.0.10
      CASSANDRA_ENDPOINT_SNITCH: PropertyFileSnitch
    ports:
      - "9042:9042" # CQL
      - "7199:7199" # JMX
    volumes:
      - ./cassandra_config/cluster_config/dc1_rack1/cassandra.yaml:/etc/cassandra/cassandra.yaml
      - ./cassandra_config/cluster_config/dc1_rack1/cassandra-jaas.config:/etc/cassandra/cassandra-jaas.config
      - ./cassandra_config/cluster_config/dc1_rack1/cassandra-rackdc.properties:/etc/cassandra/cassandra-rackdc.properties
      - ./cassandra_config/cluster_config/dc1_rack1/cassandra-topology.properties:/etc/cassandra/cassandra-topology.properties
      - ./cassandra_config/cluster_config/dc1_rack1/commitlog_archiving.properties:/etc/cassandra/commitlog_archiving.properties
      - ./cassandra_config/cluster_config/dc1_rack1/logback.xml:/etc/cassandra/logback.xml
      - ./cassandra_config/cluster_config/dc1_rack1/logback-tools.xml:/etc/cassandra/logback-tools.xml
    networks:
      vpc_bridge:
        ipv4_address: 10.0.0.10
    healthcheck:
      test: [ "CMD", "cqlsh", "--execute", "describe keyspaces" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 40s
      resources:
        reservations:
          memory: 2g
          cpus: '0.125'
        limits:
          memory: 3g
          cpus: '0.25'

  cassandra_dc1_rack2:
    container_name: dc1_rack2
    hostname: node2
    image: cassandra:4.0.4
    depends_on:
      - cassandra_dc1_rack1
    environment:
      CASSANDRA_CLUSTER_NAME: StudentsCluster
      CASSANDRA_DC: dc1
      CASSANDRA_RACK: rack2
      CASSANDRA_NUM_TOKENS: 32
      CASSANDRA_SEEDS: 10.0.0.10
      CASSANDRA_ENDPOINT_SNITCH: PropertyFileSnitch
    ports:
      - "9043:9042" # CQL
    volumes:
      - ./cassandra_config/cluster_config/dc1_rack2/cassandra.yaml:/etc/cassandra/cassandra.yaml
      - ./cassandra_config/cluster_config/dc1_rack2/cassandra-jaas.config:/etc/cassandra/cassandra-jaas.config
      - ./cassandra_config/cluster_config/dc1_rack2/cassandra-rackdc.properties:/etc/cassandra/cassandra-rackdc.properties
      - ./cassandra_config/cluster_config/dc1_rack2/cassandra-topology.properties:/etc/cassandra/cassandra-topology.properties
      - ./cassandra_config/cluster_config/dc1_rack2/commitlog_archiving.properties:/etc/cassandra/commitlog_archiving.properties
      - ./cassandra_config/cluster_config/dc1_rack2/logback.xml:/etc/cassandra/logback.xml
      - ./cassandra_config/cluster_config/dc1_rack2/logback-tools.xml:/etc/cassandra/logback-tools.xml
    networks:
      vpc_bridge:
        ipv4_address: 10.0.0.12
    healthcheck:
      test: [ "CMD", "cqlsh", "--execute", "describe keyspaces" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 40s
      resources:
        reservations:
          memory: 2g
          cpus: '0.125'
        limits:
          memory: 3g
          cpus: '0.25'

  cassandra_dc2_rack1:
    container_name: dc2_rack1
    hostname: node3
    image: cassandra:4.0.4
    depends_on:
      - cassandra_dc1_rack1
    environment:
      CASSANDRA_CLUSTER_NAME: StudentsCluster
      CASSANDRA_DC: dc2
      CASSANDRA_RACK: rack1
      CASSANDRA_NUM_TOKENS: 32
      CASSANDRA_SEEDS: 10.0.0.10
      CASSANDRA_ENDPOINT_SNITCH: PropertyFileSnitch
    ports:
      - "9044:9042" # CQL
    volumes:
      - ./cassandra_config/cluster_config/dc2_rack1/cassandra.yaml:/etc/cassandra/cassandra.yaml
      - ./cassandra_config/cluster_config/dc2_rack1/cassandra-jaas.config:/etc/cassandra/cassandra-jaas.config
      - ./cassandra_config/cluster_config/dc2_rack1/cassandra-rackdc.properties:/etc/cassandra/cassandra-rackdc.properties
      - ./cassandra_config/cluster_config/dc2_rack1/cassandra-topology.properties:/etc/cassandra/cassandra-topology.properties
      - ./cassandra_config/cluster_config/dc2_rack1/commitlog_archiving.properties:/etc/cassandra/commitlog_archiving.properties
      - ./cassandra_config/cluster_config/dc2_rack1/logback.xml:/etc/cassandra/logback.xml
      - ./cassandra_config/cluster_config/dc2_rack1/logback-tools.xml:/etc/cassandra/logback-tools.xml
    networks:
      vpc_bridge:
        ipv4_address: 10.20.114.10
    healthcheck:
      test: [ "CMD", "cqlsh", "--execute", "describe keyspaces" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 40s
      resources:
        reservations:
          memory: 2g
          cpus: '0.125'
        limits:
          memory: 3g
          cpus: '0.25'

networks:
  vpc_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/8





